---
- project:
    check:
      jobs:
        - osel-gofmt
    gate:
      jobs:
        - osel-gofmt
- job:
    name: osel-gofmt
    run: playbooks/osel-gofmt.yaml
- job:
    name: osel-gotest
    run: playbooks/osel-gotest.yaml
